# golangci-lint configuration for Beacon
# Updated: 2025-11-05
# Governance: Aligned with Beacon Constitution v1.0.0 Principle VII (Excellence)
# Configuration version: v2

version: 2

run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-files: []
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  show-stats: true

linters:
  # Use 'standard' as default linter set, then enable additional ones
  default: standard

  enable:
    # Additional linters for code quality beyond standard set
    - misspell      # Spelling mistakes in comments
    - bodyclose     # HTTP response body closure (network code)
    - gosec         # Security issues
    - revive        # Go linter replacement for golint
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code duplication
    - goconst       # Repeated strings that could be constants
    - prealloc      # Slice preallocation for performance

  disable: []

  settings:
    errcheck:
      check-type-assertions: false  # Don't check type assertions with _ = x.(Type)
      check-blank: false             # Don't check blank assignments _ = x
      exclude-functions:
        # Standard library functions where error can be safely ignored
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

        # Network cleanup - acceptable to ignore in defer/cleanup
        - (io.Closer).Close
        - (*net.Conn).Close
        - (*net.PacketConn).Close
        - (*os.File).Close
        - (net.Listener).Close

    govet:
      enable-all: true  # Enable all optional go vet analyzers
      settings:
        shadow:
          strict: true

    gocyclo:
      min-complexity: 15  # Allow moderate complexity for protocol parsing

    dupl:
      threshold: 100      # Minimum token count for duplication detection

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - .semgrep-tests  # TDD test files with intentional violations

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Exclude fieldalignment from test files - memory optimization not critical for tests
    - path: _test\.go
      linters:
        - govet
      text: "fieldalignment"

    # Exclude unusedwrite from test files - nil assignments are often for test clarity
    - path: _test\.go
      linters:
        - govet
      text: "unusedwrite"

    # Exclude unused code warnings for stub files (M2 preparation)
    - path: _stub\.go$
      linters:
        - unused
        - staticcheck
      text: "is unused|field conn is unused"

    # Exclude RFC comment lines from line length check
    - linters:
        - lll
      source: "^// RFC "

    # Allow dot imports in tests for convenience
    - path: _test\.go
      text: "dot-imports"
